#ifndef ROTT64_N64_CUSTOM_CONTENT_H
#define ROTT64_N64_CUSTOM_CONTENT_H

static const char *const rott64_custom_content[] = {
    "ARMAGON/ARMAGON.RTC",
    "ARMAGON/ULTRAROT.RTL",
    "BARDEN/KILLER.RTL",
    "BARDEN2/PSYCHO.RTL",
    "C2ROTT/CUSTOM2.RTL",
    "CHADPARK/CHADPARK.RTL",
    "CLAUSTRO/CLAUSTRO.RTL",
    "DELXSLIP/KILLER.RTL",
    "DELXSLIP/PSYCHO.RTC",
    "DELXSLIP/PSYCHO.RTL",
    "DMREVENG/DMREVENG.RTC",
    "DMRTCOMP/DMRTCOMP.RTC",
    "ENTRY/ENTRY.RTL",
    "FINLSYCO/KILLER3.RTL",
    "FINLSYCO/PSYCHO2.RTC",
    "FINLSYCO/PSYCHO3.RTL",
    "FINLSYCO/WINNT952.RTL",
    "JM1_RTC/JM1.RTC",
    "JM1RTC/JM1.RTC",
    "KILMENOW/KILMENOW.RTL",
    "LASER/LASER.RTL",
    "MIKE_RTL/MIKE.RTL",
    "NEWLEVS/RVNEW.RTC",
    "NOAR1/NOAR1.RTL",
    "OHIORTC/OHIO.RTC",
    "PLAYTIME/PLAYTIME.RTC",
    "RMD20A/EXAMPLE.RTL",
    "RMD30A/EXAMPLE.RTL",
    "ROBOTECH/ROBOTECH.RTL",
    "SETH1/DRKJRNY.RTL",
    "TOCOMBR/TOCOMBAT.RTC",
    "TOM/TOM.RTL",
    "WAR/WAR.RTL",
    "WILD/WILD.RTC",
    "WOLFROT1/WOLF1.RTL",
};
#define ROTT64_CUSTOM_CONTENT_COUNT 35u

#endif
