/* Auto-generated by tools/rott64_scan_voc_rates.py. Do not hand edit. */
#ifndef ROTT64_FX_LIMITS_GENERATED_H
#define ROTT64_FX_LIMITS_GENERATED_H

#define ROTT64_FX_MAX_FREQUENCY 11025u
#define ROTT64_FX_VOC_LUMPS_SCANNED 239u
#define ROTT64_FX_COMPATIBLE_VOC_LUMPS 239u

#endif
