#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import struct

VOC_SIGNATURE = b"Creative Voice File\x1a"


def die(msg: str) -> None:
    raise SystemExit("ERROR: " + msg)


def voc_rates(blob: bytes) -> list[int]:
    if len(blob) < 26 or not blob.startswith(VOC_SIGNATURE):
        return []
    pos = struct.unpack_from("<H", blob, 20)[0]
    if pos < 26 or pos >= len(blob):
        return []
    rates: list[int] = []
    while pos < len(blob):
        block_type = blob[pos]
        pos += 1
        if block_type == 0:
            break
        if pos + 3 > len(blob):
            return []
        block_len = blob[pos] | (blob[pos + 1] << 8) | (blob[pos + 2] << 16)
        pos += 3
        if block_len > len(blob) - pos:
            return []
        payload = blob[pos:pos + block_len]
        if block_type == 1 and block_len >= 2 and payload[1] == 0:
            denom = 256 - payload[0]
            if denom > 0:
                rate = 1_000_000 // denom
                if rate > 0:
                    rates.append(rate)
        elif block_type == 9 and block_len >= 12:
            rate = struct.unpack_from("<I", payload, 0)[0]
            bits = payload[4]
            channels = payload[5]
            codec = struct.unpack_from("<H", payload, 6)[0]
            if rate > 0 and bits == 8 and channels == 1 and codec == 0:
                rates.append(rate)
        pos += block_len
    return rates


def scan_wad(path: Path) -> tuple[int, int, list[tuple[str, int]]]:
    data = path.read_bytes()
    if len(data) < 12:
        die(f"WAD is too small: {path}")
    if data[:4] not in (b"IWAD", b"PWAD"):
        die(f"unsupported WAD magic {data[:4]!r}: {path}")
    num_lumps, dir_ofs = struct.unpack_from("<II", data, 4)
    dir_size = num_lumps * 16
    if dir_ofs > len(data) or dir_size > len(data) - dir_ofs:
        die("WAD directory is out of bounds")

    found: list[tuple[str, int]] = []
    voc_lumps = 0
    for index in range(num_lumps):
        ent = dir_ofs + index * 16
        file_ofs, size = struct.unpack_from("<II", data, ent)
        raw_name = data[ent + 8:ent + 16]
        name = raw_name.split(b"\0", 1)[0].decode("ascii", errors="replace")
        if file_ofs > len(data) or size > len(data) - file_ofs:
            die(f"lump {index} ({name}) is out of bounds")
        blob = data[file_ofs:file_ofs + size]
        if not blob.startswith(VOC_SIGNATURE):
            continue
        voc_lumps += 1
        rates = voc_rates(blob)
        if rates:
            found.append((name or f"LUMP{index}", max(rates)))

    if not found:
        die("no supported 8-bit mono Creative VOC lumps were found in the WAD")
    return voc_lumps, max(rate for _name, rate in found), found


def header_text(voc_lumps: int, max_rate: int, compatible: int) -> str:
    return f'''/* Auto-generated by tools/rott64_scan_voc_rates.py. Do not hand edit. */
#ifndef ROTT64_FX_LIMITS_GENERATED_H
#define ROTT64_FX_LIMITS_GENERATED_H

#define ROTT64_FX_MAX_FREQUENCY {max_rate}u
#define ROTT64_FX_VOC_LUMPS_SCANNED {voc_lumps}u
#define ROTT64_FX_COMPATIBLE_VOC_LUMPS {compatible}u

#endif
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("wad", type=Path)
    ap.add_argument("header", type=Path)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    voc_lumps, max_rate, found = scan_wad(args.wad)
    expected = header_text(voc_lumps, max_rate, len(found))
    if args.check:
        if not args.header.is_file():
            die(f"generated header is missing: {args.header}")
        actual = args.header.read_text(encoding="utf-8")
        if actual != expected:
            die("generated FX limit header is stale; regenerate it from DARKWAR.WAD")
    else:
        args.header.parent.mkdir(parents=True, exist_ok=True)
        args.header.write_text(expected, encoding="utf-8", newline="\n")

    highest = sorted(found, key=lambda item: (-item[1], item[0]))[:8]
    print(f"PASS: scanned {voc_lumps} VOC lumps; {len(found)} use supported 8-bit mono PCM")
    print(f"PASS: real maximum ROTT FX source rate = {max_rate} Hz")
    print("Highest-rate lumps: " + ", ".join(f"{name}={rate}" for name, rate in highest))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
